# This is a basic workflow to help you get started with Actions

name: build-and-release

# Controls when the workflow will run
on:
  # Trigger on push - when a tag is set
  push:
    tags:
      - 'v*.*.*'

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build the installer
  call-windows-build:
    uses: ./.github/workflows/build-windows.yml
    
  # Using the outputs of the build
  deploy-builds: 
    runs-on: ubuntu-latest
    needs: [call-windows-build]
    steps:
      # Download the generated app files that are part of the release
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.call-windows-build.outputs.build-file }}

      - name: Output Listing
        run: ls -la

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ needs.call-windows-build.outputs.build-file }}
