# This is a basic workflow to help you get started with Actions

name: build-linux

# Controls when the workflow will run
on:
  # this is a called workflow
  workflow_call:
    outputs:
      build-file:
        description: "The output of this build procsss"
        value: ${{ jobs.linux-build-job.outputs.install-file }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build the installer on mac
  linux-build-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Output
    outputs:
      install-file: ${{ steps.output-installer.outputs.filename }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Setup python
      - name: System Setup
        run: |
          pip3 install pyinstaller pyqt5 darkdetect pyserial

      # Build the installer
      - name: Build Linux Installer
        run: |
          cd BOSSA_GUI
          pyinstaller --onefile --clean --name BOSSA_GUI --noconsole --distpath=. --icon=BOSSA_GUI/resource/sfe_logo_sm.ico --add-binary="BOSSA_GUI/resource/sfe_logo_sm.png:." --add-data="BOSSA_GUI/resource/*:resource/" BOSSA__GUI.py
          gzip BOSSA_GUI
          mv BOSSA_GUI.gz BOSSA__GUI.linux.gz
          
      - uses: actions/upload-artifact@v3
        with:
          name: BOSSA_GUI.linux.gz
          path: BOSSA_GUI.linux.gz

      - id: output-installer
        run: echo "filename=BOSSA_GUI.linux.gz" >> $GITHUB_OUTPUT
